// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class VideoGameStoreTestsTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void conestogaVideoGameStoreRegistrationInvalidEmail()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Register")).Click();
        driver.FindElement(By.Id("Email")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("DisplayName")).Click();
        driver.FindElement(By.Id("DisplayName")).SendKeys("ethan123456");
        driver.FindElement(By.CssSelector(".pb-3")).Click();
        driver.FindElement(By.Id("Email")).SendKeys("efvccx");
        driver.FindElement(By.CssSelector(".pb-3")).Click();
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.CssSelector(".recaptcha-checkbox-border")).Click();
        driver.SwitchTo().DefaultContent();
        driver.FindElement(By.CssSelector(".button")).Click();
        Assert.That(driver.FindElement(By.CssSelector(".field-validation-error")).Text, Is.EqualTo("Please enter a proper email address"));
    }
    [Test]
    public void conestogaVideoGameStoreRegistrationPasswordDoesntMeetCriteria()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Register")).Click();
        driver.FindElement(By.Id("Email")).SendKeys("hockeyboy2002@gmail.com");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("DisplayName")).Click();
        driver.FindElement(By.Id("DisplayName")).SendKeys("Ethan Batch");
        driver.FindElement(By.CssSelector("form")).Click();
        driver.FindElement(By.Id("Email")).SendKeys("ebatch6281@conestogac.on.ca");
        driver.FindElement(By.CssSelector(".pb-3")).Click();
        driver.FindElement(By.Id("Password")).SendKeys("1234");
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.CssSelector(".recaptcha-checkbox-border")).Click();
        driver.SwitchTo().DefaultContent();
        driver.FindElement(By.CssSelector(".button")).Click();
        Assert.That(driver.FindElement(By.CssSelector(".field-validation-error")).Text, Is.EqualTo("Password doesnt meet the criteria"));
    }
    [Test]
    public void conestogaVideoGameStoreLoginInvalidUsername()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanjbatch@gmail.com");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.CssSelector(".pb-3")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("hovkwhwq");
        driver.FindElement(By.CssSelector(".pb-3")).Click();
        driver.FindElement(By.CssSelector(".pb-3")).Click();
        driver.FindElement(By.Id("Password")).SendKeys("123");
        driver.FindElement(By.CssSelector(".button")).Click();
        Assert.That(driver.FindElement(By.CssSelector(".message > p")).Text, Is.EqualTo("Profile doesnt exist"));
    }
    [Test]
    public void conestogaVideoGameStoreLoginForgotPassword()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.LinkText("Reset Password")).Click();
        driver.FindElement(By.Id("UserName")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("UserName")).Click();
        driver.FindElement(By.Id("UserName")).SendKeys("ethanbatch123");
        driver.FindElement(By.CssSelector(".button")).Click();
        Assert.That(driver.FindElement(By.CssSelector("p")).Text, Is.EqualTo("Check your email for new password"));
    }
    [Test]
    public void conestogaVideoGameStoreProfileUpdateName()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Update Profile")).Click();
        driver.FindElement(By.CssSelector(".pb-3")).Click();
        driver.FindElement(By.Id("ActualName")).SendKeys("Ethan Batch");
        driver.FindElement(By.CssSelector(".button")).Click();
        Assert.That(driver.FindElement(By.CssSelector("p")).Text, Is.EqualTo("Profile details have been updated successfully"));
    }
    [Test]
    public void conestogaVideoGameStoreProfileUpdateBirthday()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Update Profile")).Click();
        driver.FindElement(By.Id("datePicker")).Click();
        driver.FindElement(By.Id("datePicker")).SendKeys("2002-07-10");
        driver.FindElement(By.CssSelector(".button")).Click();
        Assert.That(driver.FindElement(By.CssSelector("p")).Text, Is.EqualTo("Profile details have been updated successfully"));
    }
    [Test]
    public void conestogaVideoGameStorePreferencesAddPreferences()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Add Preference")).Click();
        driver.FindElement(By.Id("FavPlatform")).Click();
        {
            var dropdown = driver.FindElement(By.Id("FavPlatform"));
            dropdown.FindElement(By.XPath("//option[. = 'XBOX']")).Click();
        }
        driver.FindElement(By.Id("FavCategory")).Click();
        {
            var dropdown = driver.FindElement(By.Id("FavCategory"));
            dropdown.FindElement(By.XPath("//option[. = 'Sci-Fi']")).Click();
        }
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Preferences List")).Click();
        Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2)")).Text, Is.EqualTo("Sci-Fi"));
        Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(3)")).Text, Is.EqualTo("XBOX"));
        Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(4)")).Text, Is.EqualTo("None"));
    }
    [Test]
    public void conestogaVideoGameStorePreferencesEditPreferences()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1536, 816);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Preferences List")).Click();
        driver.FindElement(By.LinkText("Edit")).Click();
        driver.FindElement(By.Id("FavPlatform")).Click();
        {
            var dropdown = driver.FindElement(By.Id("FavPlatform"));
            dropdown.FindElement(By.XPath("//option[. = 'PC']")).Click();
        }
        driver.FindElement(By.Id("FavPlatform")).Click();
        {
            var dropdown = driver.FindElement(By.Id("FavPlatform"));
            dropdown.FindElement(By.XPath("//option[. = 'PS']")).Click();
        }
        driver.FindElement(By.Id("FavPlatform")).Click();
        {
            var dropdown = driver.FindElement(By.Id("FavPlatform"));
            dropdown.FindElement(By.XPath("//option[. = 'PC']")).Click();
        }
        driver.FindElement(By.Id("FavCategory")).Click();
        {
            var dropdown = driver.FindElement(By.Id("FavCategory"));
            dropdown.FindElement(By.XPath("//option[. = 'Action']")).Click();
        }
        driver.FindElement(By.Id("Language")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        Assert.That(driver.FindElement(By.CssSelector("p")).Text, Is.EqualTo("Preferences have been updated successfully"));
    }
    [Test]
    public void conestogaVideoGameStoreAddressSubmitAddedAddress()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 816);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Add Address")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Ethan");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Batch");
        driver.FindElement(By.Id("phoneNumber")).Click();
        driver.FindElement(By.Id("phoneNumber")).SendKeys("2265079826");
        driver.FindElement(By.Id("streetAddress")).Click();
        driver.FindElement(By.Id("streetAddress")).SendKeys("123 Main St E");
        driver.FindElement(By.Id("province")).Click();
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'Ontario']")).Click();
        }
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2J3K4");
        driver.FindElement(By.Id("transferCheckbox")).Click();
        driver.FindElement(By.Id("newUserAddress_DeliveryInstructions")).Click();
        driver.FindElement(By.Id("newUserAddress_DeliveryInstructions")).SendKeys("leave at front door");
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Address List")).Click();
        Assert.That(driver.FindElement(By.CssSelector("td:nth-child(1)")).Text, Is.EqualTo("123 Main St E"));
    }
    [Test]
    public void conestogaVideoGameStoreAddressEditAddress()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Address List")).Click();
        driver.FindElement(By.CssSelector("tr:nth-child(2) a:nth-child(1)")).Click();
        driver.FindElement(By.Id("streetAddressEdit")).Click();
        driver.FindElement(By.Id("streetAddressEdit")).Click();
        driver.FindElement(By.Id("streetAddressEdit")).SendKeys("45 Longtitude Road W");
        driver.FindElement(By.CssSelector(".button")).Click();
        Assert.That(driver.FindElement(By.CssSelector("p")).Text, Is.EqualTo("Address has been edited successfully"));
    }
    [Test]
    public void conestogaVideoGameStoreEventRegisterForAlreadyRegisteredEvent()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Register for Events")).Click();
        driver.FindElement(By.LinkText("Register")).Click();
        var elements = driver.FindElements(By.CssSelector("p"));
        Assert.True(elements.Count > 0);
    }
    [Test]
    public void conestogaVideoGameStoreViewGamesSearch()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("View Games")).Click();
        driver.FindElement(By.Id("searchInput")).Click();
        driver.FindElement(By.Id("searchInput")).SendKeys("call of duty");
        Assert.That(driver.FindElement(By.CssSelector("td:nth-child(1)")).Text, Is.EqualTo("Call of Duty MW2"));
    }
    [Test]
    public void conestogaVideoGameStoreEventUnregisterEvent()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Register for Events")).Click();
        driver.FindElement(By.LinkText("Unregister")).Click();
        Assert.That(driver.FindElement(By.CssSelector("p")).Text, Is.EqualTo("You have been Unregistered from the Retro Video Game Con Event"));
    }
    [Test]
    public void conestogaVideoGameStoreViewGamesGameDetails()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("View Games")).Click();
        driver.FindElement(By.LinkText("Game Details")).Click();
        Assert.That(driver.FindElement(By.CssSelector("p:nth-child(4)")).Text, Is.EqualTo("Call of Duty: Modern Warfare II is a 2022 first-person shooter video game developed by Infinity Ward and published by Activision."));
    }
    [Test]
    public void conestogaVideoGameStoreGameRecommendationsAuthor()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("View Games")).Click();
        driver.FindElement(By.LinkText("Game Details")).Click();
        var elements = driver.FindElements(By.CssSelector("tr:nth-child(1) > td:nth-child(2)"));
        Assert.True(elements.Count > 0);
    }
    [Test]
    public void conestogaVideoGameStoreGameRecommendationsPrice()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("View Games")).Click();
        driver.FindElement(By.LinkText("Game Details")).Click();
        var elements = driver.FindElements(By.CssSelector("tr:nth-child(1) > td:nth-child(3)"));
        Assert.True(elements.Count > 0);
    }
    [Test]
    public void conestogaVideoGameStoreRateGamesAddRating()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("View Games")).Click();
        driver.FindElement(By.LinkText("Add Rating")).Click();
        driver.FindElement(By.Id("RatingValue")).Click();
        {
            var dropdown = driver.FindElement(By.Id("RatingValue"));
            dropdown.FindElement(By.XPath("//option[. = '5']")).Click();
        }
        driver.FindElement(By.CssSelector(".button")).Click();
        Assert.That(driver.FindElement(By.CssSelector("p")).Text, Is.EqualTo("Rating has been updated successfully"));
    }
    [Test]
    public void conestogaVideoGameStoreRateGamesViewRatingOnGame()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("View Games")).Click();
        var elements = driver.FindElements(By.CssSelector("tr:nth-child(1) > td:nth-child(4)"));
        Assert.True(elements.Count > 0);
    }
    [Test]
    public void conestogaVideoGameStoreReviewGamesAddReview()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("View Games")).Click();
        driver.FindElement(By.LinkText("Add Review")).Click();
        driver.FindElement(By.Id("reviewtext")).Click();
        driver.FindElement(By.Id("reviewtext")).SendKeys("loved playing and would play again");
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("Back")).Click();
        driver.FindElement(By.LinkText("Admin")).Click();
        driver.FindElement(By.LinkText("Pending Approval Reviews")).Click();
        Assert.That(driver.FindElement(By.CssSelector("td:nth-child(2)")).Text, Is.EqualTo("loved playing and would play again"));
    }
    [Test]
    public void conestogaVideoGameStoreReviewGamesViewReviews()
    {
        driver.Navigate().GoToUrl("https://localhost:7069/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.LinkText("Login")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("ethanbatch1234");
        driver.FindElement(By.Id("Password")).SendKeys("5965hI11*");
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Password")).Click();
        driver.FindElement(By.CssSelector(".button")).Click();
        driver.FindElement(By.LinkText("View Games")).Click();
        driver.FindElement(By.LinkText("View Reviews")).Click();
        Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(2)")).Text, Is.EqualTo("loved playing and would play again"));
    }
}
